name: nightly

on:
  schedule:
    - cron: "4 3 * * *"
  workflow_dispatch:
jobs:
  check-date:
    uses: ./.github/workflows/check-date.yml
  nightly-publish-check:
    name: Nightly publish check
    runs-on: ubuntu-latest
    needs: check-date
    if: ${{ needs.check-date.outputs.should_run != 'false' }}
  publish-nightly:
    name: Publish nightly
    runs-on: ubuntu-latest
    needs: nightly-publish-check
    uses: ./.github/workflows/release.yml
