name: on-issue

on:
  issues:
    types: [ opened, closed, reopened ]


jobs:

  on-issue:
    name: On new issue
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: |
          msg_text='${{ github.actor }} updated an issue:
            status: ${{ github.event.issue.state }} - #${{ github.event.issue.number }} ${{ github.event.issue.title }}
            https://github.com/zaneschepke/wgtunnel/issues/${{ github.event.issue.number }}'
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${msg_text}&message_thread_id=${{ secrets.TELEGRAM_TOPIC }}"
