name: on-publish

on:
  release:
    types: [ published ]


jobs:

  on-publish:
    name: On publish
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: |
          msg_text='${{ github.actor }} published a new release:
            Release: ${{ github.event.release.tag_name }}
            ${{ github.event.release.body }}
            https://github.com/zaneschepke/wgtunnel/releases/tag/${{ github.event.release.tag_name }}'
          curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' \
          -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${msg_text}&message_thread_id=${{ secrets.TELEGRAM_TOPIC }}"
