name: publish

on:
  schedule:
    - cron: "4 3 * * *"
  workflow_dispatch:
    inputs:
      track:
        type: choice
        description: "Google Play release track"
        options:
          - none
          - internal
          - alpha
          - beta
          - production
        default: none
        required: true
      release_type:
        type: choice
        description: "GitHub release type"
        options:
          - none
          - prerelease
          - nightly
          - release
        default: release
        required: true
      tag_name:
        description: "Tag name for release"
        required: false
        default: nightly
      flavor:
        type: choice
        description: "Product flavor"
        required: true
        default: full
        options:
          - fdroid
          - full
  workflow_call:
    inputs:
      flavor:
        type: string
        description: "Product flavor"
        required: false
        default: full

env:
  UPLOAD_DIR_ANDROID: android_artifacts

permissions:
  contents: write
  packages: write

jobs:
  check_commits:
    name: Check for New Commits
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.check.outputs.new_commits }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for new commits
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          NEW_COMMITS=$(git rev-list --count --after="$(date -Iseconds -d '23 hours ago')" ${{ github.sha }})
          echo "new_commits=$NEW_COMMITS" >> $GITHUB_OUTPUT

  build-fdroid:
    if: ${{ inputs.release_type == 'release' || inputs.flavor == 'fdroid' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build_type: ${{ inputs.release_type == '' && 'nightly' || inputs.release_type }}
      flavor: fdroid

  build-full:
    if: ${{ inputs.release_type == 'release' || inputs.release_type == 'nightly' || inputs.release_type == 'prerelease' || inputs.flavor == 'full' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build_type: ${{ inputs.release_type == '' && 'nightly' || inputs.release_type }}
      flavor: full

  publish:
    needs:
      - check_commits
      - build-full
    if: ${{ needs.check_commits.outputs.has_new_commits > 0 && inputs.release_type != 'none' }}
    name: publish-github
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ secrets.PAT_USERNAME }}
      GH_TOKEN: ${{ secrets.PAT }}
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y gh apksigner
      - name: Set TAG_NAME
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            echo "TAG_NAME=nightly" >> $GITHUB_ENV
            echo "RELEASE_TYPE=nightly" >> $GITHUB_ENV
          fi
      - name: Delete existing nightly release and tag
        if: ${{ github.event_name == 'schedule' || inputs.release_type == 'nightly' }}
        run: |
          echo "Checking for existing nightly release..."
          gh release view nightly && (echo "Deleting nightly release..."; gh release delete nightly --yes) || echo "No nightly release found"
          echo "Checking for existing nightly tag..."
          git fetch origin +refs/tags/nightly:refs/tags/nightly
          if git rev-parse nightly >/dev/null 2>&1; then
            echo "Deleting nightly tag..."
            git push origin :nightly
          else
            echo "No nightly tag found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Delete existing prerelease
        if: ${{ inputs.release_type == 'prerelease' }}
        run: |
          echo "Checking for existing prerelease ${{ github.event.inputs.tag_name }}..."
          gh release view ${{ github.event.inputs.tag_name }} && (echo "Deleting prerelease..."; gh release delete ${{ github.event.inputs.tag_name }} --yes) || echo "No prerelease found"
          echo "Checking for existing prerelease tag..."
          git fetch origin +refs/tags/${{ github.event.inputs.tag_name }}:refs/tags/${{ github.event.inputs.tag_name }}
          if git rev-parse ${{ github.event.inputs.tag_name }} >/dev/null 2>&1; then
            echo "Deleting prerelease tag..."
            git push origin :${{ github.event.inputs.tag_name }}
          else
            echo "No prerelease tag found"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Recreate nightly tag
        if: ${{ github.event_name == 'schedule' || inputs.release_type == 'nightly' }}
        run: |
          echo "Creating nightly tag..."
          git tag -f nightly
          git push origin nightly --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Set latest tag
        uses: rickstaa/action-create-tag@v1
        id: tag_creation
        with:
          tag: "latest"
          message: "Automated tag for HEAD commit"
          force_push_tag: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_exists_error: false
      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest: true
      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toTag: ${{ env.TAG_NAME }}
          fromTag: "latest"
          writeToFile: false
      - name: Make download dir
        run: mkdir ${{ github.workspace }}/temp
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.UPLOAD_DIR_ANDROID }}
          path: ${{ github.workspace }}/temp
      - name: Set version release notes
        if: ${{ inputs.release_type == 'release' }}
        run: |
          VERSION_NAME=$(grep "const val VERSION_NAME" buildSrc/src/main/kotlin/Constants.kt | awk -F'"' '{print $2}')
          RELEASE_NOTES="$(cat ${{ github.workspace }}/fastlane/metadata/android/en-US/changelogs/${VERSION_NAME}.txt || echo "No changelog found for ${VERSION_NAME}")"
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: On nightly release notes
        if: ${{ github.event_name == 'schedule' || inputs.release_type == 'nightly' }}
        run: |
          VERSION_NAME=$(./gradlew -q :app:printVersionName -PbuildType=nightly -Pflavor=full | grep -oP '\d+\.\d+\.\d+-nightly\+git\.\w+')
          echo "RELEASE_NOTES=Nightly build for version $VERSION_NAME" >> $GITHUB_ENV
      - name: On prerelease release notes
        if: ${{ inputs.release_type == 'prerelease' }}
        run: |
          VERSION_NAME=$(./gradlew -q :app:printVersionName -PbuildType=prerelease -Pflavor=full | grep -oP '\d+\.\d+\.\d+-beta\+git\.\w+')
          echo "RELEASE_NOTES=Testing version for $VERSION_NAME" >> $GITHUB_ENV
      - name: Get checksums
        id: checksum
        run: |
          checksums=""
          for file_path in $(find ${{ github.workspace }}/temp -type f -iname "*.apk"); do
            checksum=$(apksigner verify -print-certs $file_path | grep -Po "(?<=SHA-256 digest:) .*" | tr -d "[:blank:]")
            checksums="$checksums\n$file_path: $checksum"
          done
          echo "checksum<<EOF" >> $GITHUB_OUTPUT
          echo -e "$checksums" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ${{ env.RELEASE_NOTES }}

            SHA-256 fingerprints for the 4096-bit signing certificate:
            ```sh
            ${{ steps.checksum.outputs.checksum }}
            ```

            To verify fingerprint:
            ```sh
            apksigner verify --print-certs [path to APK file] | grep SHA-256
            ```

            ### Changelog
            ${{ steps.changelog.outputs.changes }}
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: ${{ inputs.release_type == 'prerelease' || inputs.release_type == '' || inputs.release_type == 'nightly' }}
          make_latest: ${{ inputs.release_type == 'release' }}
          files: |
            ${{ github.workspace }}/temp/*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}